services:
  backend:
    image: ghcr.io/laurisneimanis/ccore-ai-demo-backend:latest
    container_name: ccore-backend
    restart: unless-stopped
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8001
    depends_on:
      - chroma

  frontend:
    image: ghcr.io/laurisneimanis/ccore-ai-demo-frontend:latest
    container_name: ccore-frontend
    environment:
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
      STREAMLIT_SERVER_PORT: "8501"
      STREAMLIT_SERVER_ENABLE_CORS: "false"
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - backend

  chroma:
    image: chromadb/chroma:1.3.5
    container_name: ccore-chroma
    restart: unless-stopped
    volumes:
      - chroma_data:/chroma

volumes:
  chroma_data:
