services:
  backend:
    build: ../backend
    container_name: ccore-backend-dev
    volumes:
      - ../backend/app:/app/app
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8001
    depends_on:
      - chroma

  frontend:
    build: ../frontend
    container_name: ccore-frontend-dev
    ports:
      - "8501:8501"
    volumes:
      - ../frontend:/app
    depends_on:
      - backend

  chroma:
    image: chromadb/chroma:1.3.5
    container_name: ccore-chroma-dev
    volumes:
      - chroma_data:/chroma

volumes:
  chroma_data:
